import type { Metadata } from "next";
import { Outfit } from "next/font/google"; // Import the Inter font correctly
import "./globals.css";
import Providers from "@/components/Providers";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}> {/* Removed quotes around inter.className */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
