import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import the Inter font correctly
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Removed quotes around inter.className */}
        {children}
      </body>
    </html>
  );
}
